# Generated by Django 6.0.4 on 2026-05-12 23:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_remove_recipe_ingredients_ingredient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_recipes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
