# Generated by Django 6.0.5 on 2026-05-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_name',
            field=models.CharField(default='default_recipe.png', max_length=255),
        ),
    ]
